### PR TITLE
Feature/php7.4

### PR DESCRIPTION
**Pull request by bbrala**
We don't have php 8, and would love to use this. Think there is a lot of dev's, especially who are in the Drupal space who don't really have php 8 available already. <3

### CODE REVIEW

**Comment by dpi** [comment]
As discussed externally probably won't be merged. Though I'll think about whether this could be merged, and simply continue the existing php8 work as a later major version (1.x?). But still I personally wouldn't want to maintain it. 

This branch will be promoted quietly for those stuck on older versions. But I'm hoping since this project is intended to run on host, bare metal, it won't interfere with actual projects which are typically containerised to match production.

**Comment by dpi** [comment]
The code here looks functional, though certainly not as elegant as PHP 8 :P

**Comment by bbrala** [comment]
Yeah i agree it is less pretty ^^

**Comment by wimleers** [comment]
And here I am, still developing in 7.3 😎🥸

My dev env has PHP 5.6, 7.0, 7.1, 7.2 and 7.3.

Obviously this beautiful piece of software is the thing that will get me to finally make time to redo my dev env 😁

**Comment by dpi** [comment]
PHP 7 has mere weeks of support remaining. Closing this out!

in the future might look into doing a phar with support for older versions than the source it comes from. Much like phpstan, etc.

**Comment by bbrala** [comment]
Some things eventually solve themselves

**Pull request closed without merging**
